### ISSUE TITLE
Abkürzungsverzeichnis einpflegen

### ISSUE THREAD

**Issue by MichaelThom** [MichaelThom/TTT-Handbuch#13]
https://www.dropbox.com/s/3hx51ffitjcvbmw/abkuerzungsverzeichnis.tex?dl=0

**Comment by MichaelThom** [comment]
Irgendwie zerschießt es mir da ein package das Inhaltsverzeichnis -> kümmere ich mich später drum

**Comment by Stura7** [comment]
lang an den verwendeten Überschriften
